### ISSUE TITLE
[Suggestion] Add gamestages support

### ISSUE THREAD

**Issue by NordicGamerFE** [Vicious-MCModding/ExperiencedWorlds#2]
This mod in its nature would be great with gamestages support allowing for even deeper customizing like max size. configurable events that make the border grow between stages, like denylist stone dirt etc from a certain stage. i feel like a lot can be accomplished with gamestage support to take this mod even the next step up. i for sure can see this mod being very popular even more so if it had gamestages support.

**Comment by Drathonix** [comment]
Obviously this is long past expired. Gamestages support will not be added for pre-2.0.0 versions. 

If this is still a useful feature for you, let me know with a new suggestion in the [new repository](https://github.com/Drathonix/experiencedworlds2)
