### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GWSheridan** [Vicious-MCModding/ExperiencedWorlds#3]
**Describe the bug**
While loading world server crashes

**To Reproduce**
load mods into server list of mods can be found on crash report. I'm in the discord server under name gwsherdan if want to message me as well
mod list = https://pastebin.com/eDjEimGC

**Expected behavior**
server to load world sorry don't know what to type as works fine in single player no issues zero crashes in single player

**Evidence**
https://pastebin.com/DPhG5pYy

**Game Version**
Minecraft 1.19.2
**Mod Loader Version**
Forge-43.3.7
**Mod Version** 
experiencedworlds-1.19.1-1.1.6

**Comment by Drathonix** [comment]
Unfortunately I didn't notice this issue so it wasn't patched in EW1.

Support for V-1.1.6 is being dropped and switched for V-2.0.0 and we have updated to 1.21.1. If you want Experienced Worlds to be backported to 1.19.2, please let me know.

New repository for the project: [https://github.com/Drathonix/experiencedworlds2](https://github.com/Drathonix/experiencedworlds2)

Closing as this is no longer present in 2.0.0
